export const listItem: string;
export const checkbox: string;
export const name: string;
export const category: string;
export const quantity: string;
export const active: string;
export const inactive: string;
export const dark: string;
export const light: string;
